### ISSUE TITLE
Add newsletter signup form

### ISSUE THREAD

**Issue by husseinalhammad** [email-markup-consortium/emailmarkup.org#18]
As we prepare to launch the EMC's newsletter, it would be a good idea to add a signup form to the website so non-members can subscribe to it.

**Comment by anthonymzupancic** [comment]
Would love to help out with this! Any specific needs as far as where form submits to?

**Comment by husseinalhammad** [comment]
That would be great, @anthonymzupancic 

We have a Mailjet account. There are some prerequisites we need to address first (e.g. confirmation email). @megbosh has been working on these, but she's away this week. So I'll check with her when she's back and share any relevant info with you to set up the form.

**Comment by anthonymzupancic** [comment]
This is running on netlify right? So I imagine, simple sign up fields and use a netlify function for processing?

**Comment by husseinalhammad** [comment]
A Netlify function is an option, but it is likely the Mailjet's signup form allows to directly post to it. We'll find out soon!

**Comment by husseinalhammad** [comment]
No plans to add this at the moment.
