### ISSUE TITLE
Display list of Contributors on homepage

### ISSUE THREAD

**Issue by dylanatsmith** [email-markup-consortium/emailmarkup.org#4]
An earlier iteration of index.html proposed a list of contributors below the "Supporters" section. We didn't finalise the structure and deemed it not a blocker to shipping.

This issue can be closed when:
* We define the format for the list (any of name, title, company, URL, location, etc.)
* We collect all the necessary information from each listed contributor
* We add the first version of the list to index.html and ship it

**Comment by husseinalhammad** [comment]
The concept shown in #1 includes a contributors section which we can be referred to for inspiration.

**Comment by husseinalhammad** [comment]
What we can display:

## Sponsor logos
We can manage these manually

## Backers from Open Collective
We can link to an auto-generated SVG that contains a list of people/organisations that back EMC on Open Collective. Examples from Svelte's Open Collective:

1. [Backers](https://opencollective.com/svelte/backers.svg?width=1024&avatarHeight=90&button=false)
2. [Sponsors](https://opencollective.com/svelte/sponsors.svg?width=1024&limit=162&button=false)

## List of members/supporters
We can also list names of members/supporters who register their names via EMC application forms. The list of names are recorded in a Google Sheet which includes a column to mark whether an application is accepted. 

This is something we can update once a week. We can either manually export the list and dump it in the repo as JSON, or automate fetching the list (as long as we don't leak private information). After #15 is merged, we'll be able to parse the JSON and update the names on build with Astro.
