### ISSUE TITLE
www. redirect not in place

### ISSUE THREAD

**Issue by M-J-Robbins** [email-markup-consortium/emailmarkup.org#73]
I received this feedback from a site visitor so opening an issue here.
I've updated the link in the LinkedIn page but not looked at the underlying issue yet.

---

The HTTP redirects are broken for the EMC.

On the EMC LinkedIn page the address is: https://www.emailmarkup.org/

Clicking won't load the site, and you get an error.

Removing the www resolves the website correctly.

I checked the http://www/ (non-secure) and it doesn't redirect either.

The [http://](http:) (non-secure) however does redirect correctly.

**Comment by husseinalhammad** [comment]
This is not about redirects. The Netlify site is already set up to redirect www. traffic to emailmarkup.org

I have updated the DNS records for www subdomain. I may also need to update the SSL certificate (depends on how Netlify issued this when we first set up the site).

**Comment by husseinalhammad** [comment]
SSL certificate has now been updated to include the www. subdomain. @M-J-Robbins could you confirm that things are working as expected now?
